# -*- coding: utf-8 -*-
"""Unified Analysis V12 (Axis-Separated Gradient) - The Reactor Check

Automatically generated by Colab.
"""

import pandas as pd
import numpy as np
import xarray as xr
import os
import glob
import warnings

# ================= CONFIGURATION =================
# Input Folders
FOLDER_FULL      = "weather_data_2025_full"     # ERA5-Land
FOLDER_MARINE    = "weather_data_marine"        # ERA5-Global
FOLDER_CAMS      = "cams_singlelevel_data_2025" # CAMS Data

# Output Files
OUTPUT_AXIS      = "axis_gradient_results.csv"

# Suppress noisy warnings
warnings.filterwarnings("ignore")
# =================================================

def load_datasets():
    print("Indexing Weather & CAMS Data...")
    data_map = {}

    def scan(folder, tag):
        if not os.path.exists(folder): return
        files = glob.glob(os.path.join(folder, "*.nc"))
        for f in files:
            base = os.path.basename(f)
            parts = base.replace(".nc", "").split("_")
            key = None
            for i, p in enumerate(parts):
                if len(p)==4 and p.startswith("20") and p.isdigit():
                    if i+1 < len(parts) and parts[i+1].isdigit():
                        key = f"{p}-{parts[i+1]}"
                        break
            
            if key:
                if key not in data_map: data_map[key] = {}
                data_map[key][tag] = f

    scan(FOLDER_FULL, 'LAND')
    scan(FOLDER_MARINE, 'MARINE')
    scan(FOLDER_CAMS, 'CAMS')
    
    print(f"  Indexed {len(data_map)} months.")
    return data_map

def open_dataset(path):
    try: ds = xr.open_dataset(path, engine='netcdf4')
    except: ds = xr.open_dataset(path, engine='scipy')

    renames = {}
    if 'lat' in ds.dims: renames['lat'] = 'latitude'
    if 'lon' in ds.dims: renames['lon'] = 'longitude'
    
    if 'time' not in ds.dims:
        if 'valid_time' in ds.dims: renames['valid_time'] = 'time'
        elif 'forecast_reference_time' in ds.dims: renames['forecast_reference_time'] = 'time'
            
    if renames: ds = ds.rename(renames)

    if 'forecast_period' in ds.dims:
        size = ds.sizes['forecast_period'] if hasattr(ds, 'sizes') else ds.dims['forecast_period']
        if size == 1: ds = ds.squeeze('forecast_period', drop=True)
        else: ds = ds.isel(forecast_period=0, drop=True)

    return ds

def detect_saddle_orientation(ds):
    """
    Returns a DataArray:
    0 = No Saddle
    1 = NS Inflow (NS Converging, EW Diverging)
    2 = EW Inflow (EW Converging, NS Diverging)
    """
    u = ds['u10'] if 'u10' in ds else ds['10m_u_component_of_wind']
    v = ds['v10'] if 'v10' in ds else ds['10m_v_component_of_wind']
    degrees = (np.degrees(np.arctan2(v, u))) % 360
    speed = np.sqrt(u**2 + v**2)
    is_calm = speed <= 0.8 

    d = 1
    deg_N, deg_S = degrees.shift(latitude=d), degrees.shift(latitude=-d)
    deg_E, deg_W = degrees.shift(longitude=-d), degrees.shift(longitude=d)

    def check_axis_flow(neigh1, angle_to_center1, neigh2, angle_to_center2, tol=90, opp_tol=45):
        def ang_dist(a, b): return np.abs((a - b + 180) % 360 - 180)
        n1_in = ang_dist(neigh1, angle_to_center1) <= tol
        n2_in = ang_dist(neigh2, angle_to_center2) <= tol
        deg_diff = ang_dist(neigh1, neigh2)
        is_opposing = np.abs(deg_diff - 180) <= opp_tol
        return (n1_in & n2_in & is_opposing)

    # 1. Check NS Convergence (Inflow)
    # N flows South (270), S flows North (90)
    ns_conv = check_axis_flow(deg_N, 270, deg_S, 90)
    
    # 2. Check EW Convergence (Inflow)
    # E flows West (180), W flows East (0)
    ew_conv = check_axis_flow(deg_E, 180, deg_W, 0)

    # Create Mask (Focusing on Cardinal Saddles for clean axis separation)
    # Type 1: NS Inflow
    type1 = is_calm & ns_conv
    # Type 2: EW Inflow
    type2 = is_calm & ew_conv
    
    # Construct Output Array
    # We use 'where' to assign values. Priority doesn't strictly matter as they shouldn't overlap 
    # (can't converge on both axes implies sink/star, but we want saddles)
    # If both converge, it's a Sink, not a Saddle. We'll prioritize one or just sum.
    
    orientation = xr.full_like(u, 0, dtype=int)
    orientation = orientation.where(~type1, 1)
    orientation = orientation.where(~type2, 2) # Overwrites if both (rare)
    
    # Filter: Only keep if it is a saddle (so strictly one axis conv, one div ideally, 
    # but for this specific test, we just care "Which axis is flowing IN?")
    
    return orientation

def extract_axis_gradient(ds, orientation, cams_ds):
    # Mask of any valid event
    mask = (orientation > 0)
    if not mask.any(): return None
    
    # Identify Events
    events = mask.where(mask).stack(z=('time', 'latitude', 'longitude')).dropna(dim='z')
    if len(events) == 0: return None

    df = events.to_dataframe(name='Axis_Type')
    for c in ['time', 'latitude', 'longitude']:
        if c in df.columns: df = df.drop(columns=[c])
    df = df.reset_index() # columns: time, latitude, longitude, Axis_Type

    # Grid Resolution
    lats = ds['latitude'].values
    lons = ds['longitude'].values
    dlat = np.abs(lats[1] - lats[0]) if len(lats) > 1 else 0.1
    dlon = np.abs(lons[1] - lons[0]) if len(lons) > 1 else 0.1

    # CAMS Variables
    pm25_var = next((v for v in ['pm2p5', 'particulate_matter_2.5um', 'pm25'] if v in cams_ds), None)
    pm10_var = next((v for v in ['pm10', 'particulate_matter_10um'] if v in cams_ds), None)
    if not pm25_var or not pm10_var: return None

    tgt_t = xr.DataArray(df['time'].values, dims="z")
    
    # Function to sample points
    def sample_cams(lats, lons):
        tx = xr.DataArray(np.array(lons).astype(np.float64), dims="z")
        ty = xr.DataArray(np.array(lats).astype(np.float64), dims="z")
        try:
            p25 = cams_ds[pm25_var].interp(time=tgt_t, latitude=ty, longitude=tx, method='linear').values
            p10 = cams_ds[pm10_var].interp(time=tgt_t, latitude=ty, longitude=tx, method='linear').values
            return p25, p10
        except:
            return np.nan, np.nan

    # --- CENTER (Step 0) ---
    c_p25, c_p10 = sample_cams(df['latitude'].values, df['longitude'].values)
    df['PM25_Center'] = c_p25
    df['PM10_Center'] = c_p10
    
    # --- LOOP STEPS (1, 2, 3) ---
    for k in [1, 2, 3]:
        # Arrays to hold coords for Inflow and Outflow
        inflow_lats, inflow_lons = [], []
        outflow_lats, outflow_lons = [], []
        
        # We need to compute coords individually because axis depends on Axis_Type row-by-row
        # Vectorized approach:
        # Create arrays for N, S, E, W shifts
        lat_N = df['latitude'].values + k*dlat
        lat_S = df['latitude'].values - k*dlat
        lat_0 = df['latitude'].values
        
        lon_E = df['longitude'].values + k*dlon
        lon_W = df['longitude'].values - k*dlon
        lon_0 = df['longitude'].values
        
        # Type 1 (NS Inflow): Inflow=(N,S), Outflow=(E,W)
        # Type 2 (EW Inflow): Inflow=(E,W), Outflow=(N,S)
        
        # Sample N, S, E, W separately
        p25_N, p10_N = sample_cams(lat_N, lon_0)
        p25_S, p10_S = sample_cams(lat_S, lon_0)
        p25_E, p10_E = sample_cams(lat_0, lon_E)
        p25_W, p10_W = sample_cams(lat_0, lon_W)
        
        # Combine based on Axis Type
        # Axis 1 (NS In): Inflow = (N+S)/2, Outflow = (E+W)/2
        # Axis 2 (EW In): Inflow = (E+W)/2, Outflow = (N+S)/2
        
        # Inflow PM2.5
        df[f'PM25_In_Step{k}'] = np.where(df['Axis_Type']==1, (p25_N+p25_S)/2, (p25_E+p25_W)/2)
        df[f'PM10_In_Step{k}'] = np.where(df['Axis_Type']==1, (p10_N+p10_S)/2, (p10_E+p10_W)/2)
        
        # Outflow PM2.5
        df[f'PM25_Out_Step{k}'] = np.where(df['Axis_Type']==1, (p25_E+p25_W)/2, (p25_N+p25_S)/2)
        df[f'PM10_Out_Step{k}'] = np.where(df['Axis_Type']==1, (p10_E+p10_W)/2, (p10_N+p10_S)/2)

    return df

def main():
    print("--- STEP 1: Axis-Separated Gradient Analysis ---")
    data_map = load_datasets()
    all_events_list = []

    for key in sorted(data_map.keys()):
        sources = data_map[key]
        print(f"Processing {key}...", end="\r")
        
        ds_cams = None
        if 'CAMS' in sources: ds_cams = open_dataset(sources['CAMS'])
        
        if 'LAND' in sources and ds_cams is not None:
            ds = open_dataset(sources['LAND'])
            # Detect Orientation
            orientation = detect_saddle_orientation(ds)
            # Extract
            df = extract_axis_gradient(ds, orientation, ds_cams)
            if df is not None:
                all_events_list.append(df)

    if not all_events_list:
        print("\nNo events found.")
        return

    # --- COMPILE & ANALYZE ---
    full_df = pd.concat(all_events_list)
    
    # Filter for valid data and significant PM10
    full_df = full_df.dropna(subset=['PM25_Center', 'PM10_Center'])
    full_df = full_df[full_df['PM10_Center'] > 1e-9]

    # Calculate Global Background Mean (Approx)
    # Using center as reference
    
    print("\n" + "="*80)
    print("      SADDLE POINT 'REACTOR' ANALYSIS (Inflow vs Outflow)      ")
    print("="*80)
    print(f"{'Distance':<10} | {'INFLOW Ratio':<15} | {'OUTFLOW Ratio':<15} | {'Diff':<10}")
    print("-" * 80)
    
    # Center
    center_r = (full_df['PM25_Center'] / full_df['PM10_Center']).mean()
    print(f"{'Center':<10} | {center_r:.4f}          | {center_r:.4f}          | -")
    
    for k in [1, 2, 3]:
        # Inflow Stats
        in_r = (full_df[f'PM25_In_Step{k}'] / full_df[f'PM10_In_Step{k}']).mean()
        # Outflow Stats
        out_r = (full_df[f'PM25_Out_Step{k}'] / full_df[f'PM10_Out_Step{k}']).mean()
        
        diff = out_r - in_r
        print(f"{f'Step {k}':<10} | {in_r:.4f}          | {out_r:.4f}          | {diff:+.4f}")
        
    print("-" * 80)
    
    full_df.to_csv(OUTPUT_AXIS, index=False)
    print(f"Detailed axis data saved to {OUTPUT_AXIS}")

if __name__ == "__main__":
    main()